### ISSUE TITLE
Create base TangoBox VM image (operating system)

### ISSUE THREAD

**Issue by piogor** [3Controls/tangobox#1]
The image shell be:

- [x] Ubuntu 16.04 LTS, 64bit
- [x] python 2.7
- [x] User account: tango-cs, password: tango
- [x] Window manager: Metacity

**Comment by piogor** [comment]
See, wiki: https://github.com/3Controls/tangobox/wiki/Virtual-machine-structure

**Comment by cpt-majkel** [comment]
Ok, i've managed to configure VM as well as to install Ubuntu. I have a question though:

- i've  found that there are at least two ways to install Metacity: one is *GNOME Flashback Session* and another is "direct" installation with installing any neccesary packages separately. Which is better here?

**Comment by piogor** [comment]
I suggest to use _GNOME Flashback Session_

**Comment by andygotz** [comment]
I downloaded and ran the TangoBox VM on my laptop - so far so good!

Could we introduce a naming scheme like TangoBox_LTS_RCn or TangoBox_92_RCn where n increases everytime something significant changes so we can track changes.

Andy

**Comment by piogor** [comment]
Thanks @andygotz or the first test :)

@cpt-majkel , @Patfra , @stanislaw47 , lets use the naming scheme proposed by Andy. I will change the name, now for RC1.
