### ISSUE TITLE
Provide JLinac application on the VM

### ISSUE THREAD

**Issue by piogor** [3Controls/tangobox#12]
- [x] copy JLinac GUI demo from old tango-box to VM
- [x] create a link to JLinac GUI on the VM desktop
- [x] check if it works with linac simulation form #9

**Comment by Patfra** [comment]
@piogor @andygotz  @chedburgh  @Ingvord

Despite the problem with the Elinac demo (this before @sergirubio updates)  I have managed to run a Jlinac demo form old TangoBox VM on a new VM. However, devices running on DynamicSD/eleniac server (inside ``tangobox-sim`` container) keep restarting all the time (it can be seen on Jlinac demo). I am going to go thru the whole process again (I am able to easily recreate it from my notes) with patched fandango and vacca. I hope everything will be working fine then , but i have a question.
I had to download [JZMQ](https://github.com/zeromq/jzmq) to run Jlinac demo, but installing JZMQ required downloading another packages: ``autoconfig`` and ``maven``. Those are installing commands for JZMQ :
```
cd jzmq-jni/
./autogen.sh 
./configure
make
make install
cd ..
mvn package
 ```
So here is my question: Considering #27, do you accepts installing more packages on VM?

**Comment by andygotz** [comment]
The jlinac application has not been recompiled since a while. this explains why it needs jzmq I think. I will get someone to recompile it here with a new version of JTango. I suggest you wait until next week.

**Comment by andygotz** [comment]
Can you try running jlinac with JTango?

**Comment by Patfra** [comment]
No but i had to change package in ``jlinac.sh`` from **TangORB** to **JTango** and the jlinac GUI finally opened. We also used ``linac.mysqldump`` file to open backup of linac's devices settings from old VM. What's more we installed VACCA in VM and managed to run elinac GUI. All devices are running on ``tangobox-sim`` container.
