### ISSUE TITLE
Install PyTango 9.2.1 on the VM

### ISSUE THREAD

**Issue by piogor** [3Controls/tangobox#13]
- [x] PyTango installed in /usr/local
- [x] PyTango in PYTHONPATH

Use --prefix when used pip install

**Comment by cpt-majkel** [comment]
To install PyTango follow this tutorial:

- Install PyTango dependencies:
`sudo apt-get install -y libboost-all-dev`
- Install and upgrade pip
`sudo apt-get install python-pip`
`pip install --upgrade pip`
- Install numpy:
`pip install -U numpy`
- Install PyTango in **/usr/local** :
`sudo pip install --install-option="--prefix=/usr/local" pytango`
(it may take a while)
- Add entry to PYTHONPATH:
`export PYTHONPATH="${PYTHONPATH}:/my/path"`  It should be path to the folder where **.py** files are located. It should look like this:
`export PYTHONPATH="${PYTHONPATH}:/usr/local/lib/python2.7/dist-packages"`

To check if everything works fine, just type:
```
python
>>> import PyTango
>>> PyTango.Release.version
'9.2.1'
```
