### ISSUE TITLE
Install Taurus 4.1 on the VM

### ISSUE THREAD

**Issue by piogor** [3Controls/tangobox#14]
- [x] Taurus installed with prefix /usr/local
- [x] Taurus tools shortcuts available from desktop

**Comment by cpt-majkel** [comment]
To install Taurus follow this tutorial:

- Firstly, it is necessary to install all dependencies. Strictly speaking, Taurus only depends on numpy, but that will leave out most of the features normally expected of Taurus.

Install PyTango #13 
Then:
```
sudo apt-get install python-qt4
pip install spyder --user
sudo apt-get install python-guiqwt
pip install ply --user
pip install pymca5 --user
```
- Finally, Taurus itself:
`sudo pip install --install-option="--prefix=/usr/local" taurus`
