### ISSUE TITLE
Install Mambo on VM

### ISSUE THREAD

**Issue by piogor** [3Controls/tangobox#16]
Follows #15
- [x] Mambo installed on VM
- [x] Desktop link created
- [x] Example parameters from simulated linac and motors configured with Mambo for HDB
- [x] Example parameters from simulated linac and motors configured with Mambo for TDB, 2weeks buffer.
- [x] Example view presents selected parameters
- [x] History checked

**Comment by stanislaw47** [comment]
I have following problem: I can with ease login into database inside container from VM, but when I launch Mambo, it behaves like it doesn't know that it shiuld use another host. I've exported `HDB_HOST`, `HDB_NAME`, `HDB_SCHEMA` and it's TDB counterpartners but it changed nothing.
Any help appreciated
@andygotz, @chedburgh, @lzytniak @nleclercq
