### ISSUE TITLE
Install mTango and REST 

### ISSUE THREAD

**Issue by piogor** [3Controls/tangobox#23]
mTango shell be installed in a dedicated container/image `tangobox-web`.
- [x] mTango running on the container
- [x] REST api running on the container
- [x] browser links created on the VM desktop

**Comment by Patfra** [comment]
Hi @Ingvord,
I need to install tomcat on my container in order to run mTango. do you have any advise for me or maybe you know any good tutorial how to configure tomcat on ubuntu 16.04?

**Comment by Ingvord** [comment]
Hi @Patfra this must be fairly easy - it is already in the repo:

`$> sudo apt-get install tomcat8`

Just drop [latest](https://github.com/tango-controls/tango-webapp/releases) TangoWebapp.war into `/var/lib/tomcat8/webapps`

Please note that it is better to run mtangorest.server as a standalone java, see [here](https://bitbucket.org/hzgwpn/mtangorest.server/wiki/Home) how

Minimal properties to be defined:

![mtangorest server_properties](https://user-images.githubusercontent.com/11678364/31008523-bd757c5e-a504-11e7-8383-93ac7f5b9097.png)

Here is the startup script:

```bash
#!/bin/bash

TANGO_HOST=hzgxenvtest:10000
INSTANCE=$1
VERSION=rc4-2.2
WD=`pwd`

echo TANGO_HOST=$TANGO_HOST
echo INSTANCE=$INSTANCE
echo VERSION=$VERSION
echo Using Java:
echo `java -version`

XMX=1G
echo XMX=$XMX

JAVA_OPTS="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5339 -Dcom.sun.management.jmxremote.port=3339 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Xmx$XMX -Xshare:off -XX:+UseG1GC -server -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=$WD/mtango.hprof -XX:+PrintGCDetails -XX:+PrintGCTimeStamps -Xloggc:$WD/mtango.loggc -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=3"
echo JAVA_OPTS=$JAVA_OPTS

JAVA_ARGS="-DTANGO_HOST=$TANGO_HOST"
echo JAVA_ARGS=$JAVA_ARGS

/usr/bin/java $JAVA_OPTS $JAVA_ARGS -jar $WD/mtangorest.server-$VERSION.jar $INSTANCE TangoRestServer $INSTANCE & > /dev/null
```

I think this would be enough for demo purposes. 

Hope this helps!
