### ISSUE TITLE
Use official Tango icons for desktop

### ISSUE THREAD

**Issue by andygotz** [3Controls/tangobox#26]
Hi,

here are the official Tango icons to be used for the desktop and where possible the applications. These icons have beeen created by Fabienne Mengoni of the ESRF. Let us know if you need different  resolution images or there are some icons missing just let us know.

Thanks!

[tango_icons.zip](https://github.com/3Controls/tangobox/files/1317556/tango_icons.zip)

**Comment by Patfra** [comment]
I can't find icon for taurus , pogo and image for background #36  (so i used the ones from old tangobox VM).  I discovered that we haven't installed itango when trying to setup desktop icon for it, however I linked it with ipython. Should I change it? Do we have to add SardemoGUI, TaurusGUI-Demo and Synoptic Demo as well, beacause the old tangobox VM has them?

**Comment by andygotz** [comment]
Here are the latest icons including some of the missing ones.

![logviewer](https://user-images.githubusercontent.com/1167099/30849779-c16b6d4a-a2a3-11e7-9a4d-883c87a4bee2.png)
![hdb_viewer](https://user-images.githubusercontent.com/1167099/30849777-c168ac54-a2a3-11e7-8357-dbca2f2b4ed5.png)
![i-tango](https://user-images.githubusercontent.com/1167099/30849778-c1697012-a2a3-11e7-88dc-ea3d64ca308f.png)
![i-tangobis-01](https://user-images.githubusercontent.com/1167099/30849775-c1664540-a2a3-11e7-86af-d6c21c1be4c8.png)
![pogo](https://user-images.githubusercontent.com/1167099/30849780-c16b7bc8-a2a3-11e7-91a4-32946480a5a3.png)
![spoc](https://user-images.githubusercontent.com/1167099/30849776-c167cb5e-a2a3-11e7-81dd-b9765d4dbfe1.jpg)
![synopticdemo](https://user-images.githubusercontent.com/1167099/30849781-c17b15ce-a2a3-11e7-99cb-48d7dbc63f2d.png)
![atk panel-01](https://user-images.githubusercontent.com/1167099/30849782-c17ce566-a2a3-11e7-9651-47861520b2f2.png)
![atk_viewer](https://user-images.githubusercontent.com/1167099/30849784-c17ffbde-a2a3-11e7-9d82-3d45af1c0604.png)
![astor](https://user-images.githubusercontent.com/1167099/30849783-c17f65e8-a2a3-11e7-934d-fade04f18304.png)
![atk moni](https://user-images.githubusercontent.com/1167099/30849785-c1814598-a2a3-11e7-8960-67d336b0114d.png)
![hdb_configurator](https://user-images.githubusercontent.com/1167099/30849786-c189de7e-a2a3-11e7-9652-17e95448ff09.png)
![jdraw](https://user-images.githubusercontent.com/1167099/30849787-c1904778-a2a3-11e7-938e-3cf97a94b18b.png)
![jive](https://user-images.githubusercontent.com/1167099/30849788-c191a5be-a2a3-11e7-8033-b63dec01671b.png)

**Comment by Patfra** [comment]
Thank you Andy. Can you provide me with the names of icons number 4, 5, 6 and 8?

**Comment by piogor** [comment]
Icons are used, and provided in repository, too. Closing.
