### ISSUE TITLE
Virtual disk size

### ISSUE THREAD

**Issue by andygotz** [3Controls/tangobox#27]
I notice the virtual disk (.vmdk) is 12 GB in size. Is there any way to reduce this? If not we will need to inform the users that they need 12-15 GB free disk.

**Comment by piogor** [comment]
We will review the disk before releasing. To be done:
- [x] extend space available (to have more free space) (see: http://www.jochenhebbrecht.be/site/2016-07-11/windows/resizing-disk-drive-in-ubuntu-guest-system-running-a-virtual-box-windows-host-syt)
- [x] clean packages cache 
- [x] clean browser cache
- [x] check temporary folders
- [x] ... (think what else can be cleaned)
- [ ] defragment disk
- [ ] compact disk with `VBoxManage modifyhd --compact ...`

**Comment by piogor** [comment]
Defragmenting and compacting seems not having any effect.
Anyway caches and temporary files have been removed in the RC11.
