### ISSUE TITLE
Compile and install Tango Controls 9.2.5

### ISSUE THREAD

**Issue by piogor** [3Controls/tangobox#3]
- [x] Source code from tango-controls.org
- [x] Read INSTALL and README
- [x] Install dependencies - development tools (gcc, java), ZMQ, OmniOrb, MariaDB or MySQL
- [x] compile with prefix=/usr/local
- [x] Read about SystemD
- [x] Setup services for DatabaseDS, Starter

**Comment by Patfra** [comment]
@piogor, according to [this site](https://help.ubuntu.com/lts/serverguide/databases.html) ubuntu 16.04 supports MySQL. So we should use it instead of MariaDB?

**Comment by andygotz** [comment]
I would use MariaDB if possible because it has become the default for Ubuntu and Debian.

**Comment by Patfra** [comment]
Where should I install all the dependecies?

**Comment by piogor** [comment]
If dependencies are not available as native Ubuntu packages let's install them with prefix /usr/local

**Comment by Patfra** [comment]
This is a configuration I have right now (after command: ./configure --prefix=/usr/local --enable-mariadb --enable-java ):
![image](https://user-images.githubusercontent.com/11886864/30379159-dd1ddce8-9895-11e7-9686-1b182104bc1a.png)
The ZMQ was installed using commands:
```
sudo wget https://download.opensuse.org/repositories/network:/messaging:/zeromq:/release-stable/Debian_9.0/Release.key -O- | sudo apt-key add
sudo apt-get -y install libzmq3-dev
```
and java by:
```
sudo apt-get -y install default-jdk
```
Is that fine or should i changed something before installing Tango?

**Comment by piogor** [comment]
ZMQ seems to be installed correctly. 
However, I see an issue with with mysql client library (CONNECTION: failed), which prevents building of  access control, database server and database creation. You need to check if MariaDB server is running and/or username and password is provided (see README/INSTALL).

**Comment by Patfra** [comment]
With help of @piogor  and @cpt-majkel  i finally manage to get correct Tango configuration:

![image](https://user-images.githubusercontent.com/11886864/30427470-3c16c858-9950-11e7-91a1-9d7a3d9bafc7.png)

The command I used is at the buttom of the picture.

I have installed libmariadbclient-dev: 
```
sudo apt-get -y install libmariadb-client-lgpl-dev
```
and configure database following instructions from @andygotz at Tango Forum:
http://www.tango-controls.org/community/forum/c/general/installation/switching-from-mysql-to-mariadb/

**Comment by Patfra** [comment]
@Ingvord, I am having these errors when I am trying to start TangoTest server using astor:

![image](https://user-images.githubusercontent.com/11886864/30537665-e40022a4-9c6a-11e7-860a-cf35d946950a.png)

I have compared type_id of Starter, DataBase and AccessControl from my image and from the official TangoBox [image](http://www.tango-controls.org/downloads/virtual-machine/)  and i have noticed some differences:

Name---------My image--------------Offical image:
Starter---------Tango/Device_4:1.0---Tango/Device_5:1.0
DaaBase-------Tango/Device_4:1.0---Tango/Device_5:1.0
AccessControl-Tango/Device_5:1.0---Tango/Device_4:1.0

Does it should be like this? Is this the cause of my problem or is could be something else?

I have downloaded sources for Tango Controls 9.2.5 form http://www.tango-controls.org/downloads/source/

**Comment by Ingvord** [comment]
@Patfra TangoDatabaseDS must be 5.1 that is for sure. I would expect Starter to be 5.1 as well. Once this is fixed I believe the errors will gone. As they are basically indicate outdated database.

**Comment by andygotz** [comment]
I think you are right. You have an old version of the DataBase which does not support the DbGetClassPipeProperty command. You must use a more recent versions. 9.2.5 is the right one but maybe you have a version installed from the Ubuntu repository or docker which is being being started instead. Are you sure you are starting the correct version i.e. the one you compiled?

On my laptop I have for the DataBase: Tango/Device_5:1.0 and StoredProcedureRelease 1.9 (you can check this with jive on the sys/database/2 device).

**Comment by piogor** [comment]
We know the reason, it seems `apt-get install tango-db` was invoked, which installed 8.1.2 DataBaseds.

**Comment by Patfra** [comment]
I finnal manage to install Tango Controls and establish services for DataBaseDS and Starter :) I  attach [tango_installation.zip](https://github.com/3Controls/tangobox/files/1314020/tango_installation.zip) containing:
- Tango 9.2.5 installation.sh - step-by-step description of installation process
- systemd  - services files based on @Ingvord 's  [recipe](http://www.tango-controls.org/community/forum/c/general/cookbook/recipe-4-tango-with-systemd-integration/)

I had to add: ``Enviroment=MYSQL_UNIX_PORT=/var/run/mysqld/mysqld.sock `` (there is missspell in Tango 9.2.5 installation file) to some services files, because the default port was ``/tmp/mysql.sock`` , but this location doesn't existed, so it was causing an error. If there is a better solution to this matter, please let me know.
