### ISSUE TITLE
Install JupyTango

### ISSUE THREAD

**Issue by piogor** [3Controls/tangobox#31]
- [x] Contact Nicolas Leclercq - he agreed to do the task
- [x] JupyTango instalalation in `/home/tango-cs/JupyTango`
- [x] `~/bin/jupytango.sh` script too start juptyerlab

**Comment by nleclercq** [comment]
Installation done!
However, I couldn't test it cause my X11 session was too slow. Will try tomorrow with a better network link. I didn't my best to remove anything useless but the root partition (i.e. /) is now 97% full - which is a bit critical.

**Comment by andygotz** [comment]
Nicolas, thanks a million! Having the state-of-the-art developments i.e. JupyTango, will be highly appreciated by the workshop goers. 

I agree the disk being so full is a problem. I wonder what we can remove - maybe PyCharm. Could the 3-controls colleagues check that the disk is not being filled by the archive database? I would also cleanup where possible. Maybe we need to increase the disk size to 30 or 40 GBs. Is Tango ecosystem so big now?

**Comment by piogor** [comment]
Thanks! We will extends the disk.

 

Best regards,

Piotr

**Comment by nleclercq** [comment]
I'd like to improve the JupyTango kernel setup in order to provide the users with (full) itango features. A 'quick start notebook' would also be welcome I suppose. 

@piogor thanks for increasing the disk size. BTW, the amount of memory is quite low too. the VM started to swap while recompiling pytango.

**Comment by nleclercq** [comment]
Ok. The JupyTango (ipython) profile now loads itango magics at startup. I will prepare a tutorial - in the form of a notebook - as soon as RC8 is available. X11 is too slow to work remotely.  I will then upload the notebook on the 'reference' VM. 

### In case you want to try it, here's the procedure:
1. start jupyterlab using our dedicated script: `jupytango` 
2. a new browser tab is automagically opened with the right URL: `localhost:8888/lab?`
3. the very first connection to the service requires a 'token' which is printed in the jupytango console
4. once in jupyterlab, click the JupyTango icon to open a notebook with the appropriate kernel 
5. enjoy!

### Here are the JupyTango additions to itango:
#### Plotting a tango attribute
Syntax:
`pta [options] <tab for device selection> + <tab for attribute selection>`

Supported options: 
`-w` or `--width`: plot width in pixels
`-h` or `--height`: plot height in pixels

#### Monitoring a tango attribute:
Syntax:
`tm [options]  + <tab for device selection> + <tab for attribute selection>`

Supported options: 
`-w` or `--width`: plot width in pixels
`-h` or `--height`: plot height in pixels
`-p` or `--period`: plot refresh period in [0.1, 5] seconds - defaults to 1s
`-d` or `--depth`: scalar attribute history depth in [1, 3600] seconds - defaults to 900s

You can try to kill the monitored device will the JupyTango monitor is running to see how errors are handled.

**Comment by piogor** [comment]
Thanks @nleclercq, 
The RC8 is available  :).

**Comment by andygotz** [comment]
Super cool! It works "out-of-the-box"! Well done @nleclercq ! 

Only things I noticed so far are:

(o) I need to specify the TANGO_HOST otherwise it tries to connect to my host laptop database i.e.

tm //tangobox-vm:10000/sys/tg_test/1/double_image_ro

(o) the box zoom does not work (minor issue)

But already as it is it is a great demo.

If you do find time to write a notebook that would be great! I will show it to Vincent and Tiago to get their feedback.

Cheers

Andy

**Comment by andygotz** [comment]
I noticed that the pta command does not like the TANGO_HOST in the name i.e. this

pta //tangobox-vm:10000/sys/tg_test/1/float_spectrum_ro

does not work. Can this be changed easily?

**Comment by andygotz** [comment]
Problem solved! I specified TANGO_HOST=localhost:10000. Now pta and tm work without host name.

C'est urgent de rien faire!

**Comment by nleclercq** [comment]
@andygotz thanks for your feedback. 

> need to specify the TANGO_HOST 

I would expect jupytango to inherit its TANGO_HOST from the env. from which it's launched. Clearly speaking, from the `bashrc` of the tango-cs account. I consequently don't understand why you need to explicitly specify the TANGO_HOST. Does the `bashrc` exports TANGO_HOST properly?

> the box zoom does not work (minor issue)

The box zoom tool is supposed to work (i.e. the tool with the small loupe icon). What doesn't work (no action) is the selection tool (i.e. the one with the small cross on the icon). Can you confirm that there's actually a problem withe the zoom?

I will try to download the VM tomorrow and give it a try.

**Comment by piogor** [comment]
There were missing „export” statement in /etc/tangorc. 

Will be corrected in RC8a.

 

Br.

Piotr

**Comment by andygotz** [comment]
/etc/tangorc does not have export it in. Putting one will cuase problems. It is read by the tango library directly.

**Comment by piogor** [comment]
Hi, it seems that JupyTango is ready I am closing the issue. Thank you, Nicolas!

**Comment by vxgmichel** [comment]
I don't know whether it's too late for that or not, but a more stantard place for `JupyTango` would be `~/miniconda/envs/JupyTango`, with `~/miniconda` being the main conda environment.

Then the pytango workshop would include:
- a quick conda presentation: 
  * `source ~/miniconda/bin/activate`
  * `conda info`
- the creation of a fresh environment: 
  * `conda create --name tango3 --channel tango-controls itango python=3`
  * `source activate tango3`
- a demonstration of the client interface using itango:
  * `itango3`
- a demonstration of the server interface using `tango.test_context`:
  * `python -m tango.test_context test.MyTestDevice`
- a presentation of Jupyter, the ITango kernel and JupyTango kernel:
  * `source activate JupyTango && jypyter-lab`

I can help with that if necessary.
