### ISSUE TITLE
Install e-giga

### ISSUE THREAD

**Issue by piogor** [3Controls/tangobox#32]
- [x] Contact Claudio for help
- [x] E-giga installation in a tangobox-web container

**Comment by Patfra** [comment]
@piogor i have finally managed to connect Egiga to hdb database on ``tangobox-archive``. I have to change the default configuration file in egiga2m_conf.js from **hddpp** to  **hdd** and than configure hhd_conf.php

**Comment by Patfra** [comment]
Egiag working for hdb database.
Closing
