### ISSUE TITLE
Install Sardana

### ISSUE THREAD

**Issue by piogor** [3Controls/tangobox#33]
- [x] Create a dedicated container/image tangobox-sardana
- [x] Install Sardana device servers there
- [x] Install/configure example SardanaGUI/demo on the VM

**Comment by cpt-majkel** [comment]
Hi,
I've been struggling with Sardana and its GUI for almost two days and I ran out of ideas why it is crashing. (maybe a bug?). Here is what's happening:

- I installed Sardana 2.3.0 via pip (as suggested on docs website) and i create new instance in DB:

![run](https://user-images.githubusercontent.com/24622343/31169901-83cd52de-a8fa-11e7-8053-9203df3ca896.PNG) 

OR

![1](https://user-images.githubusercontent.com/24622343/31171134-fe5b4cdc-a8fe-11e7-9477-d7a943a7ecea.png)

The first warning is about the fact that this module is not supported in 16.04 but what worries me more is the third one.  Nevertheless instance is created and Astor shows that it is running. 

![po](https://user-images.githubusercontent.com/24622343/31170090-1d1db3ac-a8fb-11e7-817c-5677b2e90ac9.PNG)

- When i use *Spock* as a client, it connects to the proper Door but it has two behaviours: sometimes it works (with warnings though) and sometimes it generates a lot of errors and warnings.

![log](https://user-images.githubusercontent.com/24622343/31170244-ac357322-a8fb-11e7-8020-fcf1cf36f040.PNG)

- The same is in *SardanaGUI demo* (but this error is permament): 

![z gui](https://user-images.githubusercontent.com/24622343/31170498-8d2464ec-a8fc-11e7-9955-ecc42ed07b24.PNG)

Most of the errors is about connection and taurus issues so i suspect that something is wrong with Pool device. I've also tried reinstalling Sardana, installing it from official Git repo but with no effect. 
Is Taurus 4 supported by the latest Sardana? It is hard to find answer to this question. 
AFAIK there is another option to install Sardana: setup Pool and MacroServer separately but i've read that it is worse method.

Thanks in advance for any help.

**EDIT**
Installing it separately doesn't change a thing.

**Comment by piogor** [comment]
The issue was related to event system not to Taurus version. The solution was to change $TANGO_HOST to `tangobox-vm:10000`. See this thread on the Forum: http://www.tango-controls.org/community/forum/c/development/python/event-system-problem/ and this ticket: https://github.com/tango-controls/cppTango/issues/315
SardanaGUI is installed. Will be available in RC11.
