### ISSUE TITLE
Provide industrial simulation

### ISSUE THREAD

**Issue by piogor** [3Controls/tangobox#34]
- [ ] SimulatorDS configured to simulate containers with flows and valves
- [ ] Synoptic demo for this simulation
- [ ] TaurusGUI application for it

**Comment by sergirubio** [comment]
Hi, be sure to update to the latest fandango release (github/pypi).

**Comment by piogor** [comment]
Closing since the work is now proceeded within tango-controls organization. The issue has been copied there.
