### ISSUE TITLE
Provide documentation

### ISSUE THREAD

**Issue by piogor** [3Controls/tangobox#37]
- [x] How to install VM
- [x] Description what is installed
- [x] deployment diagram
- [x] Documentation moved to main tango-doc
- [x] Screenshots in the texts
- [x] RtD configured
- [x] PDF from RtD documentation

**Comment by piogor** [comment]
@cpt-majkel, I went through what you have written and it seems to be complete, for now. Thanks!
It will be good to add links to documentation of installed Tango tools/packages, but I may do it next week.
Then, PDF output from http://tango-controls.readthedocs.io will need to be uploaded.

**Comment by andygotz** [comment]
DId I hear documentation? Great! Where can I find it?

**Comment by piogor** [comment]
@andygotz, Preview of the RtD documentation is here: http://tangobox.readthedocs.io/en/docs/ it is linkedd to the tango-controls/tangobox fork.

**Comment by piogor** [comment]
The documentation has been moved to the main tango-doc repository. Preview may be seen here:
http://tango-controls.readthedocs.io/en/tangobox-documentation/installation/vm/tangobox-9.2.html

**Comment by piogor** [comment]
Then, in RC11 the documentation will be presented.
