### ISSUE TITLE
Docker installation

### ISSUE THREAD

**Issue by piogor** [3Controls/tangobox#4]

**Comment by stanislaw47** [comment]
Docker 17.06.2 has been installed from debian package. Additionally, it doesn't require sudo and starts at system boot by default

**Comment by stanislaw47** [comment]
To install docker:

* go [here](https://download.docker.com/linux/ubuntu/dists/xenial/pool/stable/amd64/) and download last package `Docker 17.06.2`
* then, open terminal in catalog in which you have downloaded package and type this command to install docker:
`sudo dpkg -i docker-ce_17.06.2~ce-0~ubuntu_amd64.deb`
* next step is to test whether Docker has installed correctly:
`sudo docker run hello-world`
If you can see this:
```
Hello from Docker!
This message shows that your installation appears to be working correctly.

To generate this message, Docker took the following steps:
 1. The Docker client contacted the Docker daemon.
 2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
 3. The Docker daemon created a new container from that image which runs the
    executable that produces the output you are currently reading.
 4. The Docker daemon streamed that output to the Docker client, which sent it
    to your terminal.

To try something more ambitious, you can run an Ubuntu container with:
 $ docker run -it ubuntu bash

Share images, automate workflows, and more with a free Docker ID:
 https://cloud.docker.com/

For more examples and ideas, visit:
 https://docs.docker.com/engine/userguide/
```
Docker is installed correctly.

You can see that `docker` commands require `sudo` priviliges. You can change by typing these commands:
```
sudo groupadd docker
sudo usermod -aG docker $USER
```
Restart your machine

Now test whether you still need `sudo` by typing:
`docker run hello-world`
output should be the same as above.

Last step is to allow Docker to start at system boot. It's just one command:
`sudo systemctl enable docker`

To reverse it, just change `enable` with `disable`

For more info click [here](https://docs.docker.com/engine/installation/linux/docker-ce/ubuntu/#install-from-a-package) and [here](https://docs.docker.com/engine/installation/linux/linux-postinstall/)
