### ISSUE TITLE
Tango AccessControl is not started automatically

### ISSUE THREAD

**Issue by andygotz** [3Controls/tangobox#41]
I am testing RC7 and I noticed that the Database is started but not Tango AccessControl. Then when I start  jive I cannot do anything because access control is configured but there is not AccessControl service running. How do you manage to use it? Is there some magic command I have to run first?

For the moment I cannot test much more. Any tips what I am doing wrong?

**Comment by andygotz** [comment]
itango is not installed either. Is RC7 the latest release candidate? I have lots of small details to comment on. Should I wait until you have finished the next release candidate?

**Comment by stanislaw47** [comment]
Hi @andygotz. About Tango Access Control: we thought it's finished and won't crash. It seems that the problem persists. To quickly start it, just type:
```
sudo systemctl start tango.target
```

It should do the job. We're working on a solution.

**Comment by andygotz** [comment]
OK thanks. I will try this. 

Related to this should I be testing RC7 or should I wait? I noticed a number of things were missing. When will you release a new version? Ideally if you could do this by tomorrow evening I can test it on the weekend. We need to get it to the participants by mid next week.

Andy

**Comment by stanislaw47** [comment]
Hi Andy
By tommorrow we shall realese RC_8 with 
- docker container with HDB, TDB and SNAP device servers
- configured Mambo
- configured Bensikin
- container `communication` (still WIP) with Modbus, Modbus Composer, PyPLC
- fixed Tango Access Control
- container with Linac
- Linac simualtion
- JLinac

**Comment by andygotz** [comment]
Great! I presume there will also be JupyTango (#31) ?

**Comment by stanislaw47** [comment]
Well, that question should be addressed to @nleclercq

**Comment by andygotz** [comment]
He already installed it yesterday. I just wanted to be sure that RC8 will be include it.

**Comment by stanislaw47** [comment]
If so, it should be included in RC_8

**Comment by andygotz** [comment]
What about Astor and Pogo? They need to be installed as well.

**Comment by piogor** [comment]
Currently default versions of Astor and Pogo are installed.
