### ISSUE TITLE
Creating docker-compose file

### ISSUE THREAD

**Issue by Patfra** [3Controls/tangobox#45]
Docker-compose file to run all containers an the VM
- [x] docker-compose.yml file
- [x] systemd service file for docker-compose
- [x] file on Desktop with links to each container 
Containers:
- [x] tangobox-archive
- [x] tangobox-base
- [x] tangobox-com
- [ ] tangobox-sardana
- [x] tangobox-sim
- [x] tangobox-web

**Comment by piogor** [comment]
seems to be not necessary. Closing the ticket.
