### ISSUE TITLE
New versions of tools

### ISSUE THREAD

**Issue by piogor** [3Controls/tangobox#47]
Update standard tango tools to the newest versions (check what can be updated, first)

**Comment by andygotz** [comment]
Very good! Most obvious candidates are jive, pogo, astor and atk.

**Comment by piogor** [comment]
- [x] Jive updated
- [x] Astor updated
- [x] ATKpanel updated
- [x] Pogo, see #55 
- [x] ATKCore, see #55

**Comment by piogor** [comment]
The new versions are already installed in RC9 and RC10. Closing.
