### ISSUE TITLE
Base docker image for tangobox tools

### ISSUE THREAD

**Issue by piogor** [3Controls/tangobox#5]
This image shell provide:
- [x] Ubuntu 16.04 LTS, 64bit
- [x] Python 2.7
- [x] Tango Controls
- [x] PyTango
- [x] Starter device server running as service
- [x] setup TANGO_HOST = tangobox:10000

Important: it should not start DatabaseDs as service

**Comment by stanislaw47** [comment]
According to [those](http://ftp.esrf.fr/pub/cs/tango/README.9.2.5a.txt) requirements, Tango depends on MariaDB or MySQL. But, since it's just a base docker image, I don't have to install it right?

**Comment by andygotz** [comment]
There are docker images for the Tango database but they are probably out of date.

**Comment by stanislaw47** [comment]
So I'll just add it. BTW, only `mariadb-server` is required because TangoBox is client. Am I right?

**Comment by piogor** [comment]
We do not need MariadDB in base docker image, since DataBaaseds will be run directly on VM not in container.

**Comment by stanislaw47** [comment]
How to run Docker container at the system start-up
=================================

In terminal:
`sudo gedit /etc/systemd/system/your_container_name.service`
Then just customize and paste code presented below:
```
[Unit]
Description=Service for starting your_container_name docker container
Requires=docker.socket
Requires=docker.service
After=docker.socket
After=docker.service

[Service]
ExecStartPre=/usr/bin/docker rm -f -v your_container_name
ExecStart=/usr/bin/docker run -d --name your_container_name --restart=unless-stopped your_image_name:tag

[Install]
WantedBy=multi-user.target
```

You just need to change `your_container_name` and `your_image_name:tag`. 
Only disadvantage of this approach is that container with such name must be present in the machine at the boost time.
