### ISSUE TITLE
TangoBox RC8a

### ISSUE THREAD

**Issue by piogor** [3Controls/tangobox#50]
After #48 the RC8 should be improved to make sure all services and images starts correctly with some minor fixes: 
- [x] access control properly starts or is disabled (see #51)
- [x] docker containers starts (unfortunately without archive)
- [x] desktop organized
- [x] disk size extended
- [x] new versions of tools installed

**Comment by piogor** [comment]
The image file is being exported to onedrive

**Comment by piogor** [comment]
Image uploade. Uploading to Elettra cloud in progress.

**Comment by nleclercq** [comment]
Hi where is the procedure explaining how to download and run the vm? Thanks

**Comment by piogor** [comment]
The image can be downloaded from here:  <https://1drv.ms/u/s!AlUXhMBn4oAfjaN0RDYYJwk_assj1Q> https://1drv.ms/u/s!AlUXhMBn4oAfjaN0RDYYJwk_assj1Q

To run it you need to install VirtualBox.

From VirtualBox, simply select menu File/Import Virtual Device and provide the downloaded .ova file in the dialog box  asked.

After importing it should be ready to start.

 

Be careful – on Windows machines the VirtualBox cannot run in parallel to Hyper-V. So, it has to be switched off. 

Hyper-V is often switched on by VisualStudio when Phone/Mobile devices related plugins are installed.

 

Best regards,

Piotr

**Comment by nleclercq** [comment]
Thanks @piogor

**Comment by piogor** [comment]
There is still problem with Elettra cloud disk but task ready to close.

**Comment by nleclercq** [comment]
@piogor What's the tango-cs account password?

**Comment by nleclercq** [comment]
What's the tango-cs account password? 'tango' doesn't work!
