### ISSUE TITLE
New version of TangoWebapp has been released

### ISSUE THREAD

**Issue by Ingvord** [3Controls/tangobox#58]
Hi, 

could you please update TangoWebapp to the newest version: [link](https://github.com/tango-controls/tango-webapp/releases/tag/v0.2-rc4)?

Thanks,

**Comment by Ingvord** [comment]
Hi, I have released a new version of TangoWebapp: [v0.2](https://github.com/tango-controls/tango-webapp/releases/tag/v0.2)

This one features image handling using plotly:

![tango_webapp-v0 2](https://user-images.githubusercontent.com/11678364/31136603-1996be00-a869-11e7-8f9e-8e71dbc17b9d.png)


Please include this one in TangoBox V10

Thanks,

**Comment by andygotz** [comment]
Cool! 

Is there a chance of getting support to display a spectrum of texts?

**Comment by Ingvord** [comment]
@andygotz there is always a chance [here](https://github.com/tango-controls/tango-webapp/issues/68) ;)

**Comment by Patfra** [comment]
@andygotz, can you tell me what are the steps you made to TangoWebapp starts on tangobox-web?  What should be changed or added?  I have tried with /tomcat-users, but it didn't worked.

**Comment by Ingvord** [comment]
@Patfra wait a sec, I am releasing a new version...

**Comment by Ingvord** [comment]
Done! [New release](https://github.com/tango-controls/tango-webapp/releases/tag/v0.3-rc1)

@Patfra  to run TangoWebapp just drop .war file into /var/lib/tomcat8/webapps

To run Tango REST API server (aka mtangorest.server) do:
1. Download latest .zip distribution: [link](https://bitbucket.org/hzgwpn/mtangorest.server/downloads/mtangorest.server-rc4-2.2.zip)
2. Make sure /etc/tomcat8/tomcat-users.xml has this:

```xml
<role rolename="mtango-user"/>
<user username="tango-cs" password="tango" roles="mtango-user"/>
```
3. Setup TANGO_HOST: in /etc/default/tomcat8 add TANGO_HOST=tangovm-bx:10000

4. Define TANGO_INSTANCE: /var/lib/tomcat8/webapps/tango/WEB-INF/web.xml

```xml
    <context-param>
        <param-name>tango.rest.server.instance</param-name>
        <!-- TODO set this to what ever is defined in the Tango DB e.g. sys -->
        <param-value>development</param-value>
    </context-param>
```
The later step requires tomcat to be restarted.

**NOTE** before doing anything stop tomcat and delete TangoWebapp and tango _folders_ from /var/lib/tomcat8/webapps

**Comment by Patfra** [comment]
@Ingvord, than you for quick response, and detailed instruction.
I have just 2 questions: 
In step 3 you mean: TANGO_HOST=tangobox-vm:10000,  right?
In order to stop/restart tomcat I can use  ``service tomcat8 stop``/ ``service tomcat restart`` ?

**Comment by andygotz** [comment]
service tomcat8 stop/ service tomcat restart does not work for some reason.

I used kill and then /etc/init.d/tomcat8 start

**Comment by Ingvord** [comment]
@Patfra 

> In step 3 you mean: TANGO_HOST=tangobox-vm:10000, right?

yes

> In order to stop/restart tomcat I can use service tomcat8 stop/ service tomcat restart ?

`sudo service tomcat8 stop` && `sudo service tomcat8 start`

**Comment by Ingvord** [comment]
@andygotz  works for me on amazon instance, maybe in VM something clashes with it

**Comment by Patfra** [comment]
@Ingvord I decited do reinstall tomcat8 and than I followed yours instructions and eventually I have managed to run TangoWebapp  and Tango REST API on ``tangobox-web`` (latest versions). Thank you @andygotz for your suggestions too!

**Comment by andygotz** [comment]
@Patfra sounds great! Can you upload a new RC 9b (?) with these fixes?

**Comment by Ingvord** [comment]
I have released a new version: [v0.3-rc2](https://github.com/tango-controls/tango-webapp/releases/tag/v0.3-rc2)

@andygotz  With text spectrum support:

![tango_webapp-v0 3-rc2](https://user-images.githubusercontent.com/11678364/31274341-ce1b29f8-aa92-11e7-982b-056e1ef24523.png)

**Comment by Patfra** [comment]
Great  news @Ingvord !
I will update the image with this version.

**Comment by Ingvord** [comment]
@Patfra Great! Thanks!!!

**Comment by Patfra** [comment]
@andygotz, I am adding container with configuration **TangoWebapp v0.3-rc2** to VM right now. If everything goes quickly and without unexpected errors I think I would find  some time to upload RC_9b.

**Comment by Patfra** [comment]
@Ingvord , @andygotz I am not sure why my page don't want to load:
![image](https://user-images.githubusercontent.com/11886864/31278638-0630ab98-aaa6-11e7-9e17-1b7d965554c0.png)

TangoRestServer is in State ON but the Status is "init in progress". I cna view it in browser.

**Comment by Ingvord** [comment]
@Patfra Try _ctrl+F5_

Basically this is due to .../hosts/localhost/10000 is not accessible (see status in the bottom bar). I have fixed this in [f593e36](https://github.com/tango-controls/tango-webapp/commit/e016fd7deef9f37458c82faa9a35d1a0e4423fca)

**Comment by Ingvord** [comment]
@Patfra is it OK?

**Comment by Patfra** [comment]
Thank you for suggestion @Ingvord , but still the page didn't want to load. I decided to remove all .war files form /opt/tomcat/webapps than redownload TangoWebapp.war again and suprisingly it worked! It seams that when I download it during build there was an error or something but docker-daemon didn't catch it.  Now i don't have time to check if that's true.  Now I am redownloading mtangoserver.war and hope everything would work properly than.
So the conclusion is that, after buliding image you have to log into container, remove .war, tango andTangoWebapp folders, stop tomcat, download .war files (unzip if necessary) and start tomcat again.
I think .war files need to be deployed one by one, not all at once.

**Comment by Patfra** [comment]
Quick Update 
As I thought. Redownloading all .war files and deploying them one by one solved this issune!! Now E-giga, TangoWebapp nad TangoRest are working fine :) 
Thank you @Ingvord nad @andygotz for your help once again!!
I am closing this issue.

**Comment by andygotz** [comment]
Thank you @Patfra !
