### ISSUE TITLE
Release RC10

### ISSUE THREAD

**Issue by piogor** [3Controls/tangobox#59]
The RC10 release should provide all what is needed for ICALEPCS, with the following priorities:
- [x] HDB++ #17 , #18 
- [x] Visual Studio Code #29 
- [x] E-giga #32 
- [x] Order on desktop
- [x] documenation from `doc/_build/html` copied to `Desktop/documents/manual` and its `index.html` linked from the desktop directly
- [x] `doc/_build/text/index.txt` copied to desktop and renamed as README.txt
- [x] tangobox-sardana container stopped and hidden if Sardana does not work properly
- [x] tangobox-archiving container stopped
- [x] tangobox-hdbpp container stopped
- [x] tangobox-sim container stopped
- [x] tangobox-web2 renamed to tangobox-egiga 
- [x] `/etc/hosts` updated with proper egiga container name
- [x] TangoWebApp running on tangobox-web, proper shortcut on the desktop
- [x] after export check import and if it starts as defined above (so containers listed remains stopped :) )
Optional:
- [ ] Sardana #33 
- [x] new version of WebApp #58

**Comment by piogor** [comment]
- scirpt to create containers changed name to `create-tangobox-container` and behaviour changed to restart unless stopped

**Comment by piogor** [comment]
@andy,
We are struggling with hdb++ and e-giga configuration and do not want to release VM with some parts not starting correctly. Anyway, we will do our best to release it tomorrow.

**Comment by andygotz** [comment]
I understand. I will make RC9a (with my patch for TangoWebapp)  available this afternoon. So some people can start downloading it.

Keep me informed and don't overdo it!

**Comment by sergirubio** [comment]
I have done commits to panic and vacca to solve the issues reported in RC9
Anyway, I also noticed high cpu usage by SnapExtractor ... any hint about it?

**Comment by Patfra** [comment]
``tangobox-web`` is working properly but we should have in mind modifying Dockerfile to make it automatic. Now after building and running container user have to redeploy **.war** files, see #58 .

**Comment by cpt-majkel** [comment]
@andygotz 
There is RC9b available on Onedrive. We are still working on HDB++ clients ( #18 ) but i hope that we will deal with it tomorrow. As soon as we finish, we will let you know.

**Comment by andygotz** [comment]
@cpt-majkel thanks for the update. I will not be able to download it tonight because the bandwidth in the hotel is too limited and it would take > 12 hours.  I will work with my modified RC9a for the demo tomorrow.
 
BTW I and others have noticed that VirtualBox pops up error windows at startup and occasionally during operation of the TangoBox. Do you have the same problem? What is it due to? How can we avoid this errors? They do not stop the VirtualBox from working but are confusing and a pain for the user. Thanks for any tips.

**Comment by stanislaw47** [comment]
HDB++ is now available. Sample DServers (ConfigurationManager and EventSubscriber) are running. There are also two apps, Hdb_Configurator and HDB_Viewer.

**Comment by nleclercq** [comment]
Hi guys, where is the VM release ?

**Comment by piogor** [comment]
Hi @nleclercq, here is the link https://1drv.ms/u/s!AlUXhMBn4oAfjakeJudTdUvw11zDAw
to RC9b.

**Comment by Ingvord** [comment]
@piogor and what about RC10?

**Comment by piogor** [comment]
@Ingvord , We will generate it on Thursday. Now we are checking if we can also make it ready with Canone and Sardana (thus, almost reaching the goal).

**Comment by piogor** [comment]
The image was not uploaded correctly to onedrive. To be checked on Monday.

**Comment by piogor** [comment]
@andygotz, @Ingvord, @nleclercq, @nleclercq the RC10 is available for download here: 
https://1drv.ms/u/s!AlUXhMBn4oAfjalcXPNMSJjjqwHELg
 :)

**Comment by andygotz** [comment]
Great - I am downloading it now. I will give you my feedback as soon as I have a chance to test it. Do you have any documentation for the TangoBox VM?

**Comment by piogor** [comment]
There is a link to documentation on the VM desktop.

**Comment by andygotz** [comment]
Great! I tried the VM for a short while this morning and noticed that TangoWebapp and REST api works (good!) but that the defaults stored in the TangoWebapp are wrong - they should be tangobox-web:8080 and not localhost:10001. At least on my host. I will send more feedback when I have done more tests.

**Comment by Ingvord** [comment]
@andygotz changing the defaults is a little bit tricky now:

`sudo nano /var/lib/tomcat8/webapps/TangoWebapp/apps/tango_webapp/production.js`

And change the highlighted values:

![tango_webapp_defaults](https://user-images.githubusercontent.com/11678364/31668120-9fa6dc9e-b351-11e7-958a-86ec030a6d4f.png)

But once you change them in the app just logout and login again - the app will store these values for your user and use them afterwards. So it is required to change them only once.
