### ISSUE TITLE
conda not installed

### ISSUE THREAD

**Issue by andygotz** [3Controls/tangobox#61]
Conda is not installed. I installed it with sudo pip install conda but then when I tried to install pytango3 it failed with this message:

tango-cs@TangoBox-VM:~$ conda install -c esrf-bcu pytango3
ERROR: The install method you used for conda--probably either `pip install conda`
or `easy_install conda`--is not compatible with using conda as an application.
If your intention is to install conda as a standalone application, currently
supported install methods include the Anaconda installer and the miniconda
installer.  You can download the miniconda installer from
https://conda.io/miniconda.html.

**Comment by vxgmichel** [comment]
Miniconda has actually been installed in `/home/tango-cs/JupyTango`. 

The main environment can be activated using:

```bash
$ source ~/JupyTango/bin/activate  # Activate the main conda environment
$ conda create -n tango -c esrf-bcu pytango  # Create a tango environment 
$ source activate tango  # Activate the tango environment 
```

**Comment by andygotz** [comment]
Thanks it works for python 2.7. I did not manage to get it working for python 3 but that is probably my lack of experience with conda.

**Comment by nleclercq** [comment]
The JupyTango installed on the VM is based on a (mini)conda 2 (i.e. Python 2.7) distribution. You need to install conda 3 in order to be able to install python 3 packages. Conda 2 & 3 can coexist on the same host but not in the same install directory.

**Comment by vxgmichel** [comment]
> You need to install conda 3 in order to be able to install python 3 packages

Actually no, it is possible to create a python 3 environment using miniconda 2, e.g:

```bash
$ source ~/JupyTango/bin/activate  # Activate the main conda environment
$ conda create -n tango3 -c esrf-bcu python=3 pytango  # Create a tango + python3 environment 
$ source activate tango3  # Activate the tango + python3 environment
$ python
Python 3.6.0 |Continuum Analytics, Inc.| (default, Dec 23 2016, 12:22:00)
```

**Comment by nleclercq** [comment]
Cool. I was aware of the 'env' feature but was sure that you couldn't mix 2 & 3 in the same install. Thanks.

**Comment by piogor** [comment]
Closing the issue as part of cleaning... :)
