### ISSUE TITLE
Tango-box

### ISSUE THREAD

**Issue by hasrifa2003** [3Controls/tangobox#73]
I have network problem to download more than 3GB file at once. if there any options for downloading series of file which finally could be reconstruct as Tango-box, it will very helpful.

**Comment by andygotz** [comment]
Good point. We should provide a multi-file version made with 7-zip for example. 

Piotr, can you do this? I suggest a version with Nx1 GB files.

**Comment by piogor** [comment]
@andygotz , yes, I will do this.

**Comment by hasrifa2003** [comment]
thank you very much. 
I'm waiting for RC11, and hoping it would be easily cloned to fresh desktop with minimum resources.

**Comment by piogor** [comment]
@hasrifa2003, a multiple-volumes archive is being uploaded to: https://1drv.ms/f/s!AlUXhMBn4oAfjcJlCAK62o7P92Mr7A
There will be 9 files. When it is ready I will post.
Use 7-zip to decompress the `.ova` file:

> Open the 7-zip program and browse to the folder where you have all the parts of multi-volume archive, select the first part (*.zip.001), right-click on it and select the Combine Files... option, which you can also access via File ► Combine Files... menu option. A popup window will appear, where you can recheck the file sequence of the 7-zip multi-volume archive and you can also specify the output folder for the combined single archive.
See: https://www.file-extensions.org/article/useful-information-about-multi-volume-archives for more info.

**Comment by piogor** [comment]
@hasrifa2003, The files are uploaded. Let me know if you succeed with downloads and uncompressing.

**Comment by hasrifa2003** [comment]
just finish download and resemble. 

Trying with proper result (may be):

![screenshottango9_2rc11](https://user-images.githubusercontent.com/6845752/33596279-c659ee92-d9cd-11e7-93a9-71f48186a6a8.png)

it looks heavy running on my Dell Inspiron 14 series 3000.

**Comment by hasrifa2003** [comment]
trying to move virtual to physical disk using:
sudo qemu-img convert TangoBox-9.2_RC11-disk001.vmdk -O raw /dev/sdb

result:
1. Harddisk 
![tango_vtop](https://user-images.githubusercontent.com/6845752/33869296-899a7f90-df3a-11e7-8a88-605db1b73f15.png)
2. when it boot error occur:
lvmetad is not active yet, using direct activation during sysinit
volume group "ubuntu-vg" not found
can not process volume group ubuntu-vg
.
.
.
.

is there any idea to transfer vmdk to real harddisk?.

**Comment by piogor** [comment]
Hi @hasrifa2003, I have no experience with transfer of a virtual drive to a real one but have you tried to mount the disk in other system and check if the files are there?

**Comment by piogor** [comment]
There are work on new release of the TangoBox. It will not use LVM. In respect to this the issue seems to be outdated, so I am closing it. @hasrifa2003, please reopen it, if you find I am wrong. Br.
