### ISSUE TITLE
SVG editor missing

### ISSUE THREAD

**Issue by lzytniak** [3Controls/tangobox#74]
Could you please add inkscape
`sudo apt-get install inkscape`
http://wiki.inkscape.org/wiki/index.php/Installing_Inkscape

**Comment by piogor** [comment]
Thanks @lzytniak for reporitng/asking. The related issue is created within tango-controls organization. I am closing this one, since the work is now proceeded on the tango-controls organization fork: https://github.com/tango-controls/tangobox
