### ISSUE TITLE
No module named pyqtgraph

### ISSUE THREAD

**Issue by lzytniak** [3Controls/tangobox#75]
Could you please install pyqtgraph
`pip install pyqtgraph`
http://www.pyqtgraph.org/documentation/installation.html

**Comment by piogor** [comment]
Thanks @lzytniak for reporitng/asking. The related issue is created within tango-controls organization. I am closing this one, since the work is now proceeded on the tango-controls organization fork: https://github.com/tango-controls/tangobox
