### ISSUE TITLE
TangoBox 9.2RC11 -heartbeat problems

### ISSUE THREAD

**Issue by bourtemb** [3Controls/tangobox#76]
Ryan reported an the [tango-controls forum](http://www.tango-controls.org/community/forum/c/general/development/no-heartbeat-from-dserverhdbes-server-tangobox92_rc11/?page=1#post-3572) heartbeat issues with the Tango events when using HDB++ on the TangoBox.
The network (and maybe docker) configuration should be improved in order to ensure Tango events work properly on the TangoBox.

**Comment by piogor** [comment]
Hi @bourtemb, I am transfering issues from this repo to the one in tango-controls organization.
